export enum ActionType {
    // login
    LOGIN_REQUEST = 'login/LOGIN_REQUEST',
    LOGIN_SUCCESS = 'login/LOGIN_SUCCESS',
    LOGIN_ERROR = 'login/LOGIN_ERROR',
    LOGIN_RESET = 'login/LOGIN_RESET',

    // Root Data
    GET_ROOTDATA_REQUEST = 'root/GET_ROOTDATA_REQUEST ',
    GET_ROOTDATA_SUCCESS = 'root/GET_ROOTDATA_SUCCESS',
    GET_ROOTDATA_ERROR = 'root/GET_ROOTDATA_ERROR',

    // 프로필 페이지 용 데이터
    GET_PROFILE_PAGE_DATA_REQUEST = 'profile/GET_PROFILE_PAGE_DATA_REQUEST',
    GET_PROFILE_PAGE_DATA_SUCCESS = 'profile/GET_PROFILE_PAGE_DATA_SUCCESS',
    GET_PROFILE_PAGE_DATA_ERROR = 'profile/GET_PROFILE_PAGE_DATA_ERROR',
}